---
- hosts: localhost
  connection: local
  become: true
  gather_facts: true

  tasks: 
  - name: Install Base Packages
    package: 
      name: 
        - htop
        - tmux
        - neovim
        - terminator
        - neofetch
        - zsh
        - timeshift
        - syncthing
        - caffeine
        - qemu-guest-agent

  - name: Clone ohmyzsh
      git:
      clone: yes
      repo: https://github.com/ohmyzsh/ohmyzsh.git
      dest: /home/kalifornia909/git/ohmyzsh
      update: yes

  - name: Install ohmyzsh
      shell:
      chdir: ~/git/ohmyzsh/tools
      executable: ~/git/ohmyzsh/tools/install.sh
      cmd: install.sh

  - name: Clone Powerlevel10k
      git:
      clone: yes
      repo: https://github.com/romkatv/powerlevel10k.git
      dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
      update: yes
  
  - name: Clone Nerd-Fonts
      git:
      clone: yes
      repo: https://github.com/ryanoasis/nerd-fonts.git
      dest: ~/git/nerd-fonts
      
  - name: Make Terminator Folder
      file:
      path: mkdir ~/.config/terminator/
      state: directory
      owner: kalifornia909
      group: kalifornia909
      mode: 0775

  - name: Make NeoVIM Folder
    become_user: kalifornia909
    file:
      path: mkdir ~/.config/nvim
      state: directory
      owner: kalifornia909
      group: kalifornia909
      mode: 0775

  - name: Copy Alias File
    copy:
      src: files/alias
      dest: ~/.alias
      owner: kalifornia909
      group: kalifornia909

  - name: Copy BASH File
    copy:
      src: files/bash
      dest: ~/.bashrc
      owner: kalifornia909
      group: kalifornia909

  - name: Copy ZSH File
    copy:
      src: files/zsh
      dest: ~/.zshrc
      owner: kalifornia909
      group: kalifornia909

  - name: Copy Powerlevel10k
    copy:
      src: files/p10k
      dest: ~/.p10k.zsh
      owner: kalifornia909
      group: kalifornia909

  - name: Copy NeoVIM config
    copy:
      src: files/neovim
      dest: ~/.config/nvim/init.vim
      owner: kalifornia909
      group: kalifornia909

  - name: Copy Terminator config
    copy:
      src: files/terminator
      dest: ~/.config/terminator/config
      owner: kalifornia909
      group: kalifornia909

