---
- hosts: localhost
  connection: local
  vars:
    user: "{{ lookup('env', 'USER') }}"
    home: "{{ lookup('env', 'HOME') }}"

  tasks: 
  - name: Install Base Packages
    become: true
    become_method: sudo
    package: 
      name: 
        - htop
        - tmux
        - neovim
        - terminator
        - neofetch
        - zsh
        - timeshift
        - syncthing
        - caffeine
        - spice-vdagent 

  - name: Make git Folder
    become: false
    file:
      path: "{{ home }}/git/"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0775

  - name: Make Terminator Folder
    file:
      path: "{{ home }}/.config/terminator/"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0775

  - name: Make NeoVIM Folder
    become_user: "{{ user }}"
    file:
      path: "{{ home }}/.config/nvim"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0775

  - name: Copy Alias File
    copy:
      src: files/alias
      dest: "{{ home }}/.alias"
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Copy BASH File
    copy:
      src: files/bash
      dest: "{{ home }}/.bashrc"
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Copy Powerlevel10k
    copy:
      src: files/p10k
      dest: "{{ home }}/.p10k.zsh"
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Copy NeoVIM config
    copy:
      src: files/neovim
      dest: "{{ home }}/.config/nvim/init.vim"
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Copy Terminator config
    copy:
      src: files/terminator
      dest: "{{ home }}/.config/terminator/config"
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Clone ohmyzsh
    git:
      clone: yes
      repo: https://github.com/ohmyzsh/ohmyzsh.git
      dest: "{{ home }}/git/ohmyzsh"
      update: yes

  - name: Install ohmyzsh
    shell:
      chdir: "{{ home }}/git/ohmyzsh/tools"
      executable: "{{ home }}/git/ohmyzsh/tools/install.sh"
      cmd: install.sh

  - name: Clone Powerlevel10k
    git:
      clone: yes
      repo: https://github.com/romkatv/powerlevel10k.git
      dest: "{{ home }}/.oh-my-zsh/custom/themes/powerlevel10k"
      update: yes
  
  - name: Clone Nerd-Fonts
    git:
      clone: yes
      repo: https://github.com/ryanoasis/nerd-fonts.git
      dest: "{{ home }}/git/nerd-fonts"

  - name: Install Nerd-Fonts
    shell:
      chdir: "{{ home }}/git/nerd-fonts"
      executable: "{{ home }}/git/nerd-fonts/install.sh"
      cmd: install.sh

  - name: Copy ZSH File
    copy:
      src: files/zsh
      dest: "{{ home }}/.zshrc"
      owner: "{{ user }}"
      group: "{{ user }}"