---
- hosts: localhost
  connection: local
  become: true

  vars:
    user: "{{ lookup('env', 'USER') }}"

  tasks: 
  - name: install base packages
    package: 
      name: 
        - htop
        - tmux
        - neovim
        - terminator
        - neofetch
        - pip3
        - python3
        - python3-psutil
        - zsh

  - name: copy alias file
    copy: 
      src: files/alias
      dest: ~
      owner: "{{ user }}"
      group: "{{ user }}"