---
- hosts: localhost
  connection: local
  become: true


  tasks: 
  - name: install base packages
    package: 
      name: 
        - htop
        - tmux
        - neovim
        - terminator
        - neofetch
