---
- hosts: localhost
  connection: local
  become: true


  tasks: 
  - name: install base packages
    package: 
      name: 
        - htop
        - tmux
        - neovim
        - terminator
        - neofetch
        - python3
        - pip3
        - python3-psutil
        - zsh

  - name: copy alias file
    copy: 
      src: files/alias
      dest: "{{ home }}/.alias"
      owner: "{{ user }}"
      group: "{{ group }}"