---
- hosts: localhost
  connection: local
  become: true

  vars:
    user: "{{ lookup('env', 'USER') }}"

  tasks: 
  - name: install base packages
    package: 
      name: 
        - htop
        - tmux
        - neovim
        - terminator
        - neofetch
        - zsh

  - name: copy alias file
    copy:
      src: files/alias
      dest: /home/kalifornia909/.alias
      owner: kalifornia909
      group: kalifornia909

  - name: copy bash file
    copy:
      src: files/bash
      dest: /home/kalifornia909/.bashrc
      owner: kalifornia909
      group: kalifornia909

  - name: copy zsh file
    copy:
      src: files/zsh
      dest: /home/kalifornia909/.zshrc
      owner: kalifornia909
      group: kalifornia909

  - name: ohmyzsh Copy
    become_user: kalifornia909
    git:
      clone: yes
      repo: https://github.com/ohmyzsh/ohmyzsh.git
      dest: /home/kalifornia909/git/ohmyzsh
      update: yes

  - name: install ohmyzsh
    become_user: kalifornia909
    shell:
      chdir: /home/kalifornia909/git/ohmyzsh/tools
      executable: /home/kalifornia909/git/ohmyzsh/tools/install.sh
      cmd: install.sh

  - name: powerlevel10k
    become_user: kalifornia909
    git:
      clone: yes
      repo: https://github.com/romkatv/powerlevel10k.git
      dest: /home/kalifornia909/.oh-my-zsh/custom/themes/powerlevel10k
      update: yes
  
  - name: nerd-fonts
    become_user: kalifornia909
    git:
      clone: yes
      repo: https://github.com/ryanoasis/nerd-fonts.git
      dest: /home/kalifornia909/git/nerd-fonts

  - name: install nerd nerd-fonts
    become_user: kalifornia909
    shell:
      chdir: /home/kalifornia909/git/nerd-fonts
      executable: /home/kalifornia909/git/nerd-fonts/install.sh
      cmd: install.sh

