---
- hosts: localhost
  connection: local
  become: true
  gather_facts: true

  tasks: 
  - name: Install Base Packages
    package: 
      name: 
        - htop
        - tmux
        - neovim
        - terminator
        - neofetch
        - zsh
        - timeshift
        - syncthing
        - caffeine

  - name: Clone ohmyzsh
    become_user: kalifornia909
    git:
      clone: yes
      repo: https://github.com/ohmyzsh/ohmyzsh.git
      dest: /home/kalifornia909/git/ohmyzsh
      update: yes

  - name: Install ohmyzsh
    become_user: kalifornia909
    shell:
      chdir: /home/kalifornia909/git/ohmyzsh/tools
      executable: /home/kalifornia909/git/ohmyzsh/tools/install.sh
      cmd: install.sh

  - name: Clone Powerlevel10k
    become_user: kalifornia909
    git:
      clone: yes
      repo: https://github.com/romkatv/powerlevel10k.git
      dest: /home/kalifornia909/.oh-my-zsh/custom/themes/powerlevel10k
      update: yes
  
  - name: Clone Nerd-Fonts
    become_user: kalifornia909
    git:
      clone: yes
      repo: https://github.com/ryanoasis/nerd-fonts.git
      dest: /home/kalifornia909/git/nerd-fonts

  - name: Copy Alias File
    copy:
      src: files/alias
      dest: /home/kalifornia909/.alias
      owner: kalifornia909
      group: kalifornia909

  - name: Copy BASH File
    copy:
      src: files/bash
      dest: /home/kalifornia909/.bashrc
      owner: kalifornia909
      group: kalifornia909

  - name: Copy ZSH File
    copy:
      src: files/zsh
      dest: /home/kalifornia909/.zshrc
      owner: kalifornia909
      group: kalifornia909

  - name: Copy Powerlevel10k
    copy:
      src: files/p10k
      dest: /home/kalifornia909/.p10k.zsh
      owner: kalifornia909
      group: kalifornia909

  - name: Copy NeoVIM config
    copy:
      src: files/neovim
      dest: /home/kalifornia909/.config/nvim/init.vim
      owner: kalifornia909
      group: kalifornia909

  - name: Copy Terminator config
    copy:
      src: files/terminator
      dest: /home/kalifornia909/.config/terminator/config
      owner: kalifornia909
      group: kalifornia909

  - name: Install ohmyzsh
    become_user: kalifornia909
    shell:
      chdir: /home/kalifornia909/git/nerd-fonts
      executable: /home/kalifornia909/git/nerd-fonts/install.sh
      cmd: ./install.sh