---
- hosts: localhost
  connection: local
  become: true
  gather_facts: true

  tasks: 
  - name: Install Base Packages
    package: 
      name: 
        - htop
        - tmux
        - neovim
        - terminator
        - neofetch
        - zsh
        - timeshift
        - syncthing
        - caffeine
        - qemu-guest-agent

  - name: Clone ohmyzsh
    git:
      clone: yes
      repo: https://github.com/ohmyzsh/ohmyzsh.git
      dest: $HOME/git/ohmyzsh
      update: yes

  - name: Install ohmyzsh
    shell:
      chdir: $HOME/git/ohmyzsh/tools
      executable: $HOME/git/ohmyzsh/tools/install.sh
      cmd: install.sh

  - name: Clone Powerlevel10k
    git:
      clone: yes
      repo: https://github.com/romkatv/powerlevel10k.git
      dest: $HOME/.oh-my-zsh/custom/themes/powerlevel10k
      update: yes
  
  - name: Clone Nerd-Fonts
    git:
      become_user: $USER
      clone: yes
      repo: https://github.com/ryanoasis/nerd-fonts.git
      dest: $HOME/git/nerd-fonts
      
  - name: Make Terminator Folder
    file:
      path: mkdir $HOME/.config/terminator/
      state: directory
      owner: kalifornia909
      group: kalifornia909
      mode: 0775

  - name: Make NeoVIM Folder
    become_user: kalifornia909
    file:
      path: mkdir $HOME/.config/nvim
      state: directory
      owner: kalifornia909
      group: kalifornia909
      mode: 0775

  - name: Copy Alias File
    copy:
      src: files/alias
      dest: $HOME/.alias
      owner: kalifornia909
      group: kalifornia909

  - name: Copy BASH File
    copy:
      src: files/bash
      dest: $HOME/.bashrc
      owner: kalifornia909
      group: kalifornia909

  - name: Copy ZSH File
    copy:
      src: files/zsh
      dest: $HOME/.zshrc
      owner: kalifornia909
      group: kalifornia909

  - name: Copy Powerlevel10k
    copy:
      src: files/p10k
      dest: $HOME/.p10k.zsh
      owner: kalifornia909
      group: kalifornia909

  - name: Copy NeoVIM config
    copy:
      src: files/neovim
      dest: $HOME/.config/nvim/init.vim
      owner: kalifornia909
      group: kalifornia909

  - name: Copy Terminator config
    copy:
      src: files/terminator
      dest: $HOME/.config/terminator/config
      owner: kalifornia909
      group: kalifornia909

